# Використовуємо базовий образ Python
FROM python:3.8

# Копіюємо файли у контейнер
COPY consumer.py /app/consumer.py
COPY requirements.txt /app/requirements.txt

# Встановлюємо залежності
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Запускаємо consumer.py
CMD ["python", "consumer.py"]
