version: '3.8'

services:

  mongo:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    network_mode: host
    depends_on:
      - rabbitmq
      - mongo

  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    network_mode: host
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongodata:
