# Використовуємо базовий образ Python
FROM python:3.8

# Копіюємо файли у контейнер
COPY producer.py /app/producer.py
COPY requirements.txt /app/requirements.txt

# Встановлюємо залежності
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Запускаємо producer.py
CMD ["python", "producer.py"]
